language: java
install:
  - sudo apt-get update
  - DEBIAN_FRONTEND=noninteractive sudo apt-get install -y rpm
script:
  - mvn -Pzip,rpm package
jdk:
  - openjdk8  
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk12

